### PR TITLE
#4 avoid side effects

### LINKED ISSUE #4: Side effects when creating 2 consecutive events
I think `createEvent` function is having side-effect

## Scenario

```
  const createEvent = require('aws-event-mocks');
  
  const event1 = createEvent({
    template: 'aws:s3',
    merge: {
      Records: [{
        eventName: 'ObjectCreated:Put',
        s3: {
          bucket: {
            name: 'bucket1'
          },
          object: {
            key: 'key1'
          }
        }
      }]
    }
  });

  const event2 = createEvent({
    template: 'aws:s3',
    merge: {
      Records: [{
        eventName: 'ObjectCreated:Put',
        s3: {
          bucket: {
            name: 'bucket1'
          },
          object: {
            key: 'key2'
          }
        }
      }]
    }
  });

  console.log(event1.Records[0].s3.object.key);
  // return 'key2'
```

## Expected

I would expect to return `'key1'`

### PR DESCRIPTION
**Pull request by piercus**
Hello, 

This pull request aim to fix #4 issue.

### CODE REVIEW

**Comment by piercus** [comment]
any update ?

**Comment by piercus** [comment]
@nikgraf can you please review this PR and give me your feedback ?

Thanks

**Comment by nikgraf** [comment]
@piercus sorry for the late reply. I don't work at Serverless anymore and don't have any permissions to merge this PR.

please reach out to @eahefnawy, @pmuens, @plfx or @mthenw

**Comment by piercus** [comment]
@nikgraf thanks for the feedback

@eahefnawy, @pmuens, @plfx or @mthenw , any help would be appreciated :-)

**Review by eahefnawy — APPROVED** [review]
Looks good! Thanks guys! 🙌

**Comment by petermorlion** [comment]
Any chance of this being published to npm?

**Pull request merged**
